config/routes.rb
Rails.application.routes.draw do



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get '/home', to: 'home#index'
  get '/contact_us', to: 'home#contact', as: 'contact'
  get '/sign_up', to: 'users#new', as: 'sign_up'
  get '/login', to: 'session#new', as: 'login'
  get '/user', to: 'users#show', as: 'user'

  post '/contact_us', to: 'home#create'
  post '/sign_up', to: 'users#create' , as: 'users'
  post '/login', to: 'session#create', as:'user_login'
  get '/logout', to: 'session#destroy' , as:'logout'
  get '/map' , to: 'users#map'
  post '/rent', to: 'rentals#create' , as:'rental'
  get 'user/reservation', to: 'rentals#current', as:'current'
  post '/drop' , to:'rentals#drop' , as: 'drop'
  get '/user/history', to:'rentals#history', as:'history'
  get '/history', to:'rentals#show'
  # get '/user/map', to: 'users#map'
end

#practicing github
#practicing github 2.0

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/local.rb
class Local < ApplicationRecord

has_many :vehicle
has_many :rental

end

app/models/rental.rb
class Rental < ApplicationRecord


  belongs_to :user
  belongs_to :vehicle
  belongs_to :local

end

app/models/user.rb
class User < ApplicationRecord

validates :email,:first_name,:last_name,:password,presence: true
validates :password , length: {minimum:6}
validates :email , uniqueness: {message: "This email : %{value} already exists" }
  has_secure_password
  has_many :rental

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  validates :local_id,presence: true ,on: :update , if: :max_vehicles

belongs_to :local
has_many :rental
def max_vehicles

local= Local.find(self.local_id)
if local.max.to_i < local.vehicle.count+1
  p 'nope'
false
else
  p 'okay'
true
end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def logged_in?
    !current.nil?
  end
  def login(user,lat,lng)
    session[:user_id]=user.id
    session[:lat]=lat
    session[:lng]=lng
    cookies[:lat]=session[:lat]
    cookies[:lng]=session[:lng]
  end
  def current
    cookies[:lat]=session[:lat]
    cookies[:lng]=session[:lng]
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def has_reserved?
    !reserved.nil?
  end

  def reserved
  @current=current
  @rental =@current.rental.where("drop_date = 'nill'")
  if @rental.count == 0
    @rental=nil
    else
    @rental
  end

  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	 
	end




end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action  do
      if !session[:user_id]
      redirect_to login_path
    end
   end
   before_action only:[:current] do
     if !reserved?
      redirect_to user_path
    end
   end
def create
rental=params_rental
rental[:user_id]=session[:user_id]
rental[:drop_date]='nill'
@rental=Rental.new(rental)
if(@rental.save)
redirect_to current_path
end
end
def current
  @user=User.find(session[:user_id])
  @rental=Rental.new
  @locals=Local.all
  @current_rental=@user.rental.where("drop_date = 'nill'")
  @vehicle=@current_rental[0].vehicle
  @local=@current_rental[0].local
end
def show
  @history=[]
@rentals=User.find(session[:user_id]).rental.where("drop_date != 'nill' ")
@rentals.each do |r|
  @vehicle=r.vehicle
  @local_start=r.local
  @local_end=Local.find_by_id(r.local_drop.to_i)
  @history.push({rental:r,vehicle:@vehicle,local_start:@local_start,local_end:@local_end})

end
render json: {status: 'SUCCESS' , data: @history}, status: :ok
end

def drop
@rental=Rental.find(params_drop[:rental_id])
if @rental.vehicle.update(local_id:params_drop[:local_id])
  if @rental.update(drop_date:Date.today.to_time.to_s)
    @rental.update(local_drop:params_drop[:local_id])
  redirect_to user_path
else
  flash[:error_current]='error try again'
  redirect_to current_path
end
else
flash[:error_current]='pick another location this one is full'
redirect_to current_path

end
end

def params_rental
params.permit(:local_id,:vehicle_id)

end
def params_drop
  params.require(:rental).permit(:local_id,:rental_id,:vehicle_id)
end
def reserved?
    @rental =User.find(session[:user_id]).rental.where("drop_date = 'nill'")
  if @rental.count == 0
    nil
    else
    @rental
  end
end
def history
@user=User.find(session[:user_id])
end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action only: [:new ,:create] do
      if logged_in?
      redirect_to user_path
    end
  end

  def new
    @user=User.new
  end
  def create
  @user=User.find_by(email:params_login[:email])
    if(@user && @user.authenticate(params_login[:password]))
      login(@user,params_login[:lat],params_login[:lng])
      redirect_to user_path
    else
      flash[:login_error]="Wrong Combination of Username and Password"
      redirect_to login_path
    end
  end
  def destroy
    reset_session
    current=nil
    redirect_to login_path
  end
  private def params_login
    params.permit(:email,:password,:lat,:lng)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action only:[:show] do
  if !logged_in?
    redirect_to login_path
end
 end
 before_action only:[:show] do
   if has_reserved?
     redirect_to current_path
 end
  end


 before_action only:[:new] do
   if logged_in?
     redirect_to user_path
   end
  end

  def index
  end

  def new
    @user = User.new
  end

  def show
@user=current
  end


  def create
    
    @user = User.new({first_name:user_params[:first_name],last_name:user_params[:last_name],email:user_params[:email],password:user_params[:password]})
    if(@user.save)
      login(@user,user_params[:lat],user_params[:lng])
    redirect_to user_path
  else
    flash[:user_error] =@user.errors.full_messages
    redirect_to  sign_up_path
  end
  end


  def edit
  end

  def destroy
  end
  
  def map
  @positions=  ActiveRecord::Base.connection.execute("SELECT *,(((acos(sin((#{cookies['lat'].to_f} * pi()/180)) *
            sin((CAST(lat AS DOUBLE PRECISION) * pi()/180))+cos((#{cookies['lat'].to_f} * pi()/180)) *
            cos((CAST(lat AS DOUBLE PRECISION) *pi()/180)) * cos(((#{cookies['lng'].to_f} - CAST(lng AS DOUBLE PRECISION))*
            pi()/180))))*180/pi())*60*1.1515
        ) as distance FROM locals ORDER BY distance ASC limit 15")
@locals=[]
@positions.each do |p|
  @rented=Rental.where("drop_date = 'nill'").pluck(:vehicle_id)
  if @rented == []
  @rented=[0]
end
 @vehicles=Local.find(p['id']).vehicle.where('id not in (?)',@rented)
 @locals.push({position:p , vehicles:@vehicles})
end
    render json: {status: 'SUCCESS' , data: @locals}, status: :ok

  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :lat, :lng )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="keywords" content="">
        <meta name="description" content="">

        <title>ScootWee</title>

        <!-- Loading Bootstrap -->
        <link href="css/bootstrap.css" rel="stylesheet">

        <!-- Loading Template CSS -->
        <link href="css/animate.css" rel="stylesheet">
        <link href="css/style-magnific-popup.css" rel="stylesheet">
         <link href="css/style.css" rel="stylesheet">

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">

        <!-- Awsome Fonts -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="css/pe-icon-7-stroke.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyDAfwCoggPDi6ucFfluBOo9kpJHoFbaVtM
&ibraries=geometry,places', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--begin header -->
    <% s=controller.controller_name+'#'+controller.action_name %>
  <% if ["users#show","rentals#history","rentals#current"].include? s %>

    <header class="header">

        <!--begin nav -->
        <nav class="navbar navbar-default navbar-fixed-top">

            <!--begin container -->
            <div class="container">

                <!--begin navbar -->
                <div class="navbar-header">

                    <button data-target="#navbar-collapse-02" data-toggle="collapse" class="navbar-toggle" type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!--logo -->
                    <a href="/" class="navbar-brand" id="logo">ScootWee</a>

                </div>

                <div id="navbar-collapse-02" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li id='user_nav'><a href="/user"><%= @user.first_name%></a></li>
                        <li id='history_nav'><a href="/user/history">History</a></li>
                        <li><a href="/logout">log_out</a></li>


                    </ul>
                </div>
                <!--end navbar -->

            </div>
    		<!--end container -->

        </nav>
    	<!--end nav -->

    </header>
    <% else %>
    <header class="header">

        <!--begin nav -->
        <nav class="navbar navbar-default navbar-fixed-top">

            <!--begin container -->
            <div class="container">

                <!--begin navbar -->
                <div class="navbar-header">

                    <button data-target="#navbar-collapse-02" data-toggle="collapse" class="navbar-toggle" type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!--logo -->
                    <a href="/" class="navbar-brand" id="logo">ScootWee</a>

                </div>

                <div id="navbar-collapse-02" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#home_wrapper">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#services">Services</a></li>
                        <li><a href="#team">Team</a></li>
                        <li><a href="#gallery">Gallery</a></li>
                        <li><a href="#pricing">Pricing</a></li>
                        <li><a href="#contact">Contact</a></li>

                    </ul>
                </div>
                <!--end navbar -->

            </div>
    		<!--end container -->

        </nav>
    	<!--end nav -->

    </header>
      <% end %>
    <div class='container'>

  <%= yield %>
    </div>



    <!--end contact-->

    <!--begin footer -->
    <div class="footer">

        <!--begin container -->
        <div class="container">

            <!--begin row -->
            <div class="row">

                <!--begin col-md-12 -->
                <div class="col-md-12 text-center">

                    <!--begin copyright -->
                    <div class="copyright">
                        <p>Copyright © 2018 </p>

                    </div>
                    <!--end copyright -->

                    <!--begin footer_social -->
                    <ul class="footer_social">
                        <li>
                            <a href="#">
                                <i class="fa fa-twitter fa-3x"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-facebook fa-3x"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-instagram fa-3x"></i>
                            </a>
                        </li>

                    </ul>
                    <!--end footer_social -->

                </div>
                <!--end col-md-6 -->

            </div>
            <!--end row -->

        </div>
        <!--end container -->

    </div>
  </body>
</html>

app/views/rentals/current.html.erb
<div class='contaner'>
  <% if flash[:error_current] %>
  <div class='alert alert-danger'>
    <p><%=flash[:error_current] %></p>
  </div>
  <% end %>
<div class=' col-lg-3 col-md-offset-2' id='reservation'>
<p><img src='https://thescooterfarm.com/wp-content/uploads/2017/07/Chilli-Pro-Scooter-Reaper-Wave1.jpg' style='width:60%' ><br> <%= @vehicle.description %> @ <%= @local.street %> , <%= @local.city %> , <%= @local.state %> | <%= @local.zip_code %> Show this acces code</p>
<p><strong><img src=" https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=<%=@vehicle.sn%>"></strong><button class="btn btn-primary btn-lg" id='drop' style="margin-left:2em">Drop </button> </p>
<p></p>
</div>
<div class=' col-lg-5 col-md-offset-1' id='user#map' style='height:60vh'>
<input type='hidden' name='local_lng' value=<%=@local.lng %> >
  <input type='hidden' name='local_lat' value=<%=@local.lat %> >
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Drop Position</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      <%= form_with url: drop_path,model:@rental,id:'drop_form', class:'form col-lg-12' do |t|%>
<div class='form-group'>
<%= t.select :local_id  do%>
  <% @locals.each do |l| %>
  <%= content_tag(:option ,l.name,value: l.id) %>
  <% end %>
  <% end %>
      <%= t.hidden_field :rental_id, :value => @current_rental[0].id %>
      <%= t.hidden_field :vehicle_id, :value => @vehicle.id %>
</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id='dropit' >Confirm</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/rentals/history.html.erb
<table id='show_history' class='table table-bordered'>
  <tr class='info'>
  <th>
  Vehicle
  </th>
  <th>
  picked_in
  </th>
  <th>
  dropped_in
  </th>
  <th>
  Date reserved
  </th>
  <th>
  Date droped
  </th>
  <th>
  Show in map
  </th>

</tr>

</table>

app/views/session/new.html.erb
<div class='col-lg-12 container'>
  <% if flash[:login_error] %>
  <div class='alert alert-danger' >
    <p><%= flash[:login_error]%></p>
  </div>
  <% end %>
<%= form_with mode:@user , id:'login',class: 'form' do |t|%>

<div class= 'col-lg-6 col-md-offset-3'>
<div class= ''>

  <h1>Login</h1>

<div class='form-group '>
<%= t.label :email , 'Email' %>
<br>
<%= t.text_field :email , placeholder:'Email here',class:'form-control' %>
</div>

<div class='form-group'>
<%= t.label :password, 'Password' %>
<br>
<%= t.password_field :password , placeholder:'Password',class:'form-control' %>
</div>

<%= t.hidden_field :lat %>
<%= t.hidden_field :lng %>
<br>
<%= t.submit 'Login' ,class:'form-control btn btn-primary' %>
<% end %>
</div>

</div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<div class='container'>
  <div class='row'>
    <div class= 'col-md-6 col-md-offset-3' >
    <%= image_tag "ScootweeLogo.png",style:'margin-left:5em' %>
    </div>

  </div>
    <div class='row'>
<div class='col-lg-4 col-md-12 col-md-offset-1'>
<%= form_with url:user_login_path, id:'login' do |l|%>



<div class = ''>

<div class = ''>
  <h1>LOGIN</h1>
  <div class='form-group'>
    <%= l.label :email %>
    <br>
    <%= l.text_field :email, placeholder: "Email",class:'form-control' %>
  </div>
  <div class='form-group'>
    <%= l.label :password %>
    <br>
    <%= l.password_field :password, placeholder: "Password",class:'form-control' %>
  </div>
  <%= l.hidden_field :lat%>
  <%= l.hidden_field :lng%>
  <br>
  <%= l.submit "Login" ,class:'form-control btn btn-info' %>


  <% end %>
</div>
</div>


</div>
<div class='line col-md-2 col-md-offset-1 hidden-xs hidden-sm '>

</div>
<div class='col-lg-4 col-md-12 '>
<% if(flash[:user_error]) %>
<div class='alert alert-danger'>
<%  flash[:user_error].each do |e|  %>

<p class='text-warning'><%= e  %></p>

<% end %>
</div>
<% end %>
<%= form_with model:@user , id:'signup' do |f|%>


  <h1> SIGN UP </h1>
<div class= 'form-group'>
    <%= f.label :first_name %>
    <br>
    <%= f.text_field :first_name, placeholder: "First Name" ,class:'form-control'%>
  </div>

  <div class='form-group'>
    <%= f.label :last_name %>
    <br>
    <%= f.text_field :last_name, placeholder: "Last Name" ,class:'form-control'  %>
  </div>

  <div class='form-group'>
    <%= f.label :email %>
    <br>
    <%= f.text_field :email, placeholder: "Email" ,class:'form-control'%>
  </div>

  <div class='form-group'>
    <%= f.label :password %>
    <br>
    <%= f.password_field :password, placeholder: "Password",class:'form-control' %>
  </div>
<%= f.hidden_field :lat%>
<%= f.hidden_field :lng%>
<br>
  <%= f.submit "Sign Up" ,class:'form-control btn btn-primary' %>
<% end %>


</div>
</div>
<div>

app/views/users/show.html.erb
<div id='page' class='contaienr col-lg-12'>
<div class='row'>
<h2>Hours Of Operation: 7AM - 9PM</h2>
<br>

<h4>Choose Date</h4>
<br>

<div class='date'>
<input class='day' type="text" data-provide='datepicker' >
</div>
</div>

<div class='row' style='margin-top:2em'>


<div class= 'listandmap'>

<div id='list' class='col-lg-6' >

</div>
<div id='map' class='col-lg-5'></div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirm reservation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class='info-vl'></div>
      <%= form_with url: rental_path,id:'reservation_form' do |t| %>
      <%= t.hidden_field :local_id %>
      <%= t.hidden_field :vehicle_id %>

      </div>
      <div class="modal-footer">
        <button type="button" id="reserve" class="btn btn-primary">Reserve</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  <% end %>
      </div>
    </div>
  </div>


</div>
</div>
</div>